### ISSUE TITLE
handle partially missed data

### ISSUE THREAD

**Issue by jmagnotti** [beauchamplab/rave#16]
We currently have data is_loaded check when module is loading to ask user if they want to read a particular data type. Could this same approach be used to assess if the data are available at all? That way even if a user didn't have (for example) access to the phase information, they could still run modules that only require power. Currently, the program crashes on the select data screen with an error from hd5fr saying file cannot be found.

**Comment by dipterix** [comment]
Basically the goal of this issue is to allow "partial data". For example, users might only have phase data. The goal is to load whatever users have into RAVE with less validity checking. 

There are two advantages:

1. Allow users who can convert already preprocessed data to RAVE format
2. Allow partially copy the data (e.g. users can only copy power data if they don't use phase)

To achieve this goal there are two major tasks: One is to implement less strict checking; the other is to have error handlers to avoid crashing.

- [ ] Add less strict mode to load subject (less data checks)
- [ ] Add error handlers to avoid crashing when data is broken
- [ ] Test

**Comment by dipterix** [comment]
@jmagnotti 

Check the following updates. I'm testing the code. 
[#5a09c5](https://github.com/beauchamplab/rave/commit/5a09c510af79348193b6424050ff8724b8ae5ca9) and [#c316ed](https://github.com/beauchamplab/rave/commit/c316ed88b5c97d267c5946320c6f9400b616b980)
