### ISSUE TITLE
RAVE install error

### ISSUE THREAD

**Issue by satra** [beauchamplab/rave#48]
following the instructions on the wiki,  i'm running into an install error:

```
ERROR: dependency ‘rave’ is not available for package ‘ravebuiltins’
* removing ‘/opt/conda/lib/R/library/ravebuiltins’
Warning messages:
1: In i.p(...) :
  installation of package ‘fftwtools’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/tmp/RtmpOOhBpX/filec34d80ec92/rave_1.0.2.tar.gz’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/tmp/RtmpOOhBpX/filec346b11e6b/ravebuiltins_0.1.1.tar.gz’ had non-zero exit status
```

system: "Ubuntu 20.04.2 LTS"
R version 4.0.3

also if there is a new Docker image/Dockerfile that shows how to install the tool automatically would be much appreciated.

**Comment by jmagnotti** [comment]
Thanks for posting this error. It may be that the system doesn't have the `fftw` library installed. Can you try to install it through the package manager?
```
 sudo apt-get install libfftw3-dev libfftw3-doc
```

If this works we'll be sure to update the Linux install instructions and work on updating the docker image as well.

**Comment by satra** [comment]
thanks @jmagnotti - i installed conda's r-fftwtools package and then the error i get is:

```
Cannot create directory at '/data/rave_data/cache_dir' 
Error : Cannot create directory at '/data/rave_data/cache_dir'
```

any idea why it's trying to write to `/data` and how i can have it not use that location. i'm trying to do this without any superuser privileges.

**Comment by jmagnotti** [comment]
Thanks for reporting this further issue. Sounds like the installer isn't detecting the home directory correctly... We'll have to dig into this a bit and get back to you. Is this a fairly vanilla Ubuntu install?

**Comment by satra** [comment]
> Sounds like the installer isn't detecting the home directory correctly..

do you save any config info somewhere. if so i was playing with various environments including running the rave docker image. so it could have created some files somewhere that i should perhaps remove.

> Is this a fairly vanilla Ubuntu install?

yes we are just building of the latest iteration of the jupyter datascience container and i'm doing things inside a conda environment that has various R packages installed.

**Comment by dipterix** [comment]
Hi, @satra . Thanks for reporting this installation issue. We develop RAVE on osx, and the instructions on Linux is a little bit out-dated. I'm sorry for the inconvenience. We just tested installing RAVE on Ubuntu 20.04. The updates will be posted pretty soon. @jmagnotti could also set up a zoom call to troubleshoot the issue.

Normally `rave` sets it data repository under your home address. I remember the only place that I manually set the data repo is in the docker images. Therefore I guess you were trying to use the Dockerfile to install on your native linux or conda system. If this is what you have tried out, it is highly recommended that you reset `rave` option.

You can either use R command to reset, or go to the settings file to reset.

### R command solution

Open R (in your terminal, type "R" and return) or RStudio console, type and return

```r
raveio::raveio_resetopt()
```

This should reset your rave configurations. Then you can use `rave::rave_options()` to launch the browser to edit.

### Direct editing

You can find under the settings yaml file under `~/.config/R/raveio`. Open with text editor, then you should be able to find something like this:

```
data_dir: /home/pi/rave_data/data_dir
delay_input: 20.0
test_mode: no
py2_path: ''
py_virtualenv: ''
session_string: AfvMGMQ0sv0mQ9n
..temp: []
module_root_dir: ~/rave_modules/
verbose_level: DEBUG
file_structure: native
module_lookup_file: ~/rave_modules/modules.csv
image_height: 768
disable_startup_speed_check: no
py3_path: ''
suma_nodes_per_electrodes: 42
rave_ver: 1.0.2
bids_data_dir: /home/pi/rave_data/bids_dir/
max_mem: 7.6301994
drive_speed:
- 250.0
- 120.0
server_time_zone: America/Chicago
fast_cache: yes
raw_data_dir: /home/pi/rave_data/raw_dir
image_width: 1280
max_worker: 3
```

Correct `data_dir`, `raw_data_dir`, and probably `bids_data_dir`. 

* `data_dir`: directory containing all processed data (main repository)
* `raw_data_dir`: directory of raw data
* `bids_data_dir` (optional): root directory of BIDS-ieeg directory

You can also set maximum number of workers by changing `max_worker`. If you are setting up RAVE for shared use, please set it to `1` to save the memory

<hr>

### After the fix

Once the configuration file is fixed, you probably need to finalize installation in R (since the original installation failed).

(In your R console, run the following lines one by one)

```r
if(!require(ravebuiltins)){ remotes::install_github("beauchamplab/ravebuiltins@migrate2") }
library(rave)
rave::finalize_installation()
```

This will download RAVE builtin modules, 3D viewer data, and plug them into RAVE.

You should then be able to launch RAVE via R code:

```r
rave::start_rave()
```

If you want to download some demo subjects, run the following R code. It will download from [this page](https://github.com/beauchamplab/rave/releases/tag/v0.1.8-beta) 

```r
# You can change YAB to KC, YAD, YAI, YAF, YAH...
options('timeout' = 1e10); rave::download_sample_data("YAB")
```

**Comment by satra** [comment]
@dipterix - thanks so much for this. indeed it was me playing around with the docker image that caused the issue. i now have rave working on dandi hub ! (@yarikoptic @bendichter) the ideal thing would be to have a docker image for rave since the install process takes a bit of time. 

i was also able to get the current released docker image working (the image also says v1.0.2 - so does it mean its the same version as what i installed with the commands).

in the hub terminal you can do
```
singularity pull docker://beauchamplab/rave

# this is not necessary, but i wanted to fully isolate rave
mkdir -p home
mkdir -p home/data
mkdir -p home/jovyan

singularity exec --env NCPUS=4 -e --no-home -B $(pwd)/home:/home -B $(pwd)/home/data:/data rave_latest.sif start_rave
```

and then point the browser to: `https://hub.dandiarchive.org/user/YOURUSERID/proxy/6767/` (the last / is important for rave to find the relevant pieces)


![image](https://user-images.githubusercontent.com/184063/121979676-a2f95f00-cd58-11eb-95bb-e96fc70b44f3.png)
